#!/usr/bin/env bash
# Regenerates assets/gtky-manifest.js by scanning the band/subject/language folders.
# Run this from the gtky/ directory whenever you add or remove worksheet images.
set -euo pipefail
cd "$(dirname "$0")"

lang_code() { case "$1" in english) echo en;; spanish) echo es;; vietnamese) echo vi;; *) echo "$1";; esac; }

out=assets/gtky-manifest.js
{
  echo "/* AUTO-GENERATED by build-manifest.sh — do not edit by hand. */"
  echo "window.GTKY_MANIFEST = ["
  for band in k-2 3-5 6-8 9-12; do
    [ -d "$band" ] || continue
    while IFS= read -r f; do
      rel="${f#./}"
      subject=$(echo "$rel" | cut -d/ -f2)
      langdir=$(echo "$rel" | cut -d/ -f3)
      base=$(basename "$rel" .png)
      grade="${base#gtky-${subject}-}"
      grade="${grade%-${langdir}}"
      # Optional variant marker: gtky-<subject>-<grade>-v<N>-<lang>.png keeps <grade> clean.
      variant=""
      if [[ "$grade" =~ ^(.*)-v([0-9]+)$ ]]; then
        grade="${BASH_REMATCH[1]}"; variant="v${BASH_REMATCH[2]}"
      fi
      code=$(lang_code "$langdir")
      pdf="${rel%.png}.pdf"
      printf '  { "band": "%s", "subject": "%s", "grade": "%s", "variant": "%s", "lang": "%s", "file": "%s", "pdf": "%s" },\n' \
        "$band" "$subject" "$grade" "$variant" "$code" "$rel" "$pdf"
    done < <(find "./$band" -type f -name '*.png' | sort)
  done
  echo "];"
} > "$out"
echo "Wrote $out ($(grep -c '"band"' "$out") entries)"
