#!/usr/bin/env node
/* build-pd.js — assemble the teacher professional-development i18n bundles.
   Reads  _pd/<core>/<lang>.json  for each dataset and language present,
   writes assets/<global>-i18n.js exposing window.<GLOBAL> = {en:{...}, es:{...}, ...}.
   Missing languages simply fall back to English at render time (BreakoutI18n). */
const fs = require('fs');
const path = require('path');
const ROOT = __dirname;
const LANGS = ['en', 'es', 'vi', 'ar', 'hi', 'ur', 'zh'];
const SETS = [
  { dir: 'udl-core',   global: 'PD_UDL',   out: 'udl-core-i18n.js' },
  { dir: 'elps-core',  global: 'PD_ELPS',  out: 'elps-core-i18n.js' },
  { dir: 'guide-core', global: 'PD_GUIDE', out: 'guide-core-i18n.js' },
  { dir: 'suite',      global: 'PD_SUITE', out: 'pd-suite-i18n.js' },
];

for (const s of SETS) {
  const bundle = {};
  for (const lang of LANGS) {
    const fp = path.join(ROOT, '_pd', s.dir, lang + '.json');
    if (!fs.existsSync(fp)) continue;
    bundle[lang] = JSON.parse(fs.readFileSync(fp, 'utf8'));
  }
  const outPath = path.join(ROOT, 'assets', s.out);
  fs.writeFileSync(outPath,
    '/* Auto-generated by build-pd.js — do not edit by hand. Source: _pd/' + s.dir + '/*.json */\n' +
    'window.' + s.global + ' = ' + JSON.stringify(bundle) + ';\n');
  console.log(s.out + ': [' + Object.keys(bundle).join(',') + ']');
}
