#!/usr/bin/env node
const fs=require('fs'),path=require('path'),ROOT=__dirname,LANGS=['en','es','vi','ar','hi','ur','zh'];
const data={};for(const l of LANGS){const fp=path.join(ROOT,'_skills',l+'.json');if(fs.existsSync(fp))data[l]=JSON.parse(fs.readFileSync(fp,'utf8'));}
const grades=Object.keys(data.en.grades);
for(const g of grades){const dict={};for(const l of LANGS){if(!data[l])continue;dict[l]=(data[l].grades&&data[l].grades[g])||{};}
fs.writeFileSync(path.join(ROOT,g,'i18n-skills.js'),'/* Auto-generated by build-skills.js */\nBreakoutI18n.register("science-'+g+'-skills", '+JSON.stringify(dict)+');\n');}
console.log('build-skills: '+grades.length+' files, langs ['+Object.keys(data).join(', ')+']');
