#!/usr/bin/env node
/* build-toc.js — write science/i18n-toc.js from _toc/<lang>.json. */
const fs=require('fs'),path=require('path'),ROOT=__dirname,LANGS=['en','es','vi','ar','hi','ur','zh'];
const dict={};for(const l of LANGS){const fp=path.join(ROOT,'_toc',l+'.json');if(fs.existsSync(fp))dict[l]=JSON.parse(fs.readFileSync(fp,'utf8'));}
fs.writeFileSync(path.join(ROOT,'i18n-toc.js'),'/* Auto-generated by build-toc.js — science TOC language dictionary. */\nBreakoutI18n.register("science-toc", '+JSON.stringify(dict)+');\n');
console.log('build-toc: languages ['+Object.keys(dict).join(', ')+']');
