#!/usr/bin/env node
/* build-hubs.js — write each grade hub's i18n-index.js from _hub/<lang>.json.
   Merges the shared chrome + that grade's content per language and registers it
   under 'science-grade<G>-index'. Re-run after editing/translating _hub/*.json. */
const fs = require('fs');
const path = require('path');
const ROOT = __dirname;
const LANGS = ['en', 'es', 'vi', 'ar', 'hi', 'ur', 'zh'];

const data = {};
for (const l of LANGS) {
  const fp = path.join(ROOT, '_hub', l + '.json');
  if (fs.existsSync(fp)) data[l] = JSON.parse(fs.readFileSync(fp, 'utf8'));
}
const grades = Object.keys(data.en.grades);

for (const g of grades) {
  const dict = {};
  for (const l of LANGS) {
    if (!data[l]) continue;
    const shared = data[l].shared || {};
    const gc = (data[l].grades && data[l].grades[g]) || {};
    dict[l] = Object.assign({}, shared, gc);
  }
  const gnum = g.replace('grade', '');
  fs.writeFileSync(path.join(ROOT, g, 'i18n-index.js'),
    '/* Auto-generated by build-hubs.js — grade ' + gnum + ' hub language dictionary. */\n' +
    'BreakoutI18n.register(' + JSON.stringify('science-' + g + '-index') + ', ' + JSON.stringify(dict) + ');\n');
}
console.log('build-hubs: wrote ' + grades.length + ' i18n-index.js, languages [' + Object.keys(data).join(', ') + ']');
