#!/usr/bin/env node
/* build-i18n.js — zip native translations onto the English breakout structure.
   Reads:  grade<G>/locales/grade<G>.js  (featured, English window.BREAKOUT)
           grade<G>/more.js              (concept set, English window.MORE + MORE_BASE_UI)
           _i18n/grade<G>/<lang>.json    (translated TEXT only, per language)
   Writes: grade<G>/locales/grade<G>-i18n.js   (augments window.BREAKOUT.UI/CONTENT)
           grade<G>/more-i18n.js                (window.MORE_I18N for the player)

   Only TEXT is translated; every gameplay field (id, ico, type, color, len,
   answerIndex, items[].strong + order, pads[].k/.c, seq/digit answer) is copied
   verbatim from English, so translations can never corrupt gameplay. Word-lock
   answers become the translated variants PLUS the English ones (fallback).
   Run:  node breakouts/science/build-i18n.js <K|1-8>
   Output is written via JSON.stringify → always valid JS, no quote-escaping traps. */
const fs = require('fs');
const path = require('path');
const ROOT = __dirname;
const LANGS = ['es', 'vi', 'ar', 'hi', 'ur', 'zh'];

const grade = String(process.argv[2] || '').trim().toUpperCase();
if (!/^([1-8]|K)$/.test(grade)) { console.error('Usage: node build-i18n.js <K|1-8>'); process.exit(1); }
const GDIR = path.join(ROOT, 'grade' + grade);

function loadEng(file, globalName) {
  const w = { window: {} };
  eval('(function(window){' + fs.readFileSync(file, 'utf8') + '})(w.window)');
  return w.window[globalName];
}
function readI18n(lang) {
  const fp = path.join(ROOT, '_i18n', 'grade' + grade, lang + '.json');
  if (!fs.existsSync(fp)) return null;
  return JSON.parse(fs.readFileSync(fp, 'utf8'));
}

// zip translated text onto an English clue/lock, keeping every gameplay field.
function zipClues(enClues, tClues) {
  return enClues.map((c, i) => {
    const t = (tClues && tClues[i]) || {};
    return Object.assign({}, c, { nm: t.nm ?? c.nm, title: t.title ?? c.title, body: t.body ?? c.body });
  });
}
function zipLocks(enLocks, tLocks) {
  return enLocks.map((l, i) => {
    const t = (tLocks && tLocks[i]) || {};
    const out = Object.assign({}, l, { title: t.title ?? l.title, q: t.q ?? l.q, reason: t.reason ?? l.reason });
    if (l.type === 'mc' && Array.isArray(t.options)) out.options = l.options.map((o, j) => t.options[j] ?? o);
    if (l.type === 'multi' && Array.isArray(t.items)) out.items = l.items.map((it, j) => Object.assign({}, it, { t: t.items[j] ?? it.t }));
    if (l.type === 'seq' && Array.isArray(t.pads)) out.pads = l.pads.map((p, j) => Object.assign({}, p, { e: t.pads[j] ?? p.e }));
    if (l.type === 'word') {
      const tw = Array.isArray(t.word) ? t.word : (typeof t.word === 'string' && t.word ? [t.word] : []);
      out.answer = [...new Set([...tw, ...l.answer])];
    }
    return out;
  });
}

// ---- featured breakout ----------------------------------------------------
const B = loadEng(path.join(GDIR, 'locales', 'grade' + grade + '.js'), 'BREAKOUT');
const featOut = {};
for (const lang of LANGS) {
  const data = readI18n(lang);
  if (!data || !data.featured) continue;
  const f = data.featured;
  featOut[lang] = {
    UI: Object.assign({}, B.UI.en, data.chrome || {}, f.ui || {}),
    CONTENT: { clues: zipClues(B.CONTENT.en.clues, f.clues), locks: zipLocks(B.CONTENT.en.locks, f.locks) },
  };
}
const featPath = path.join(GDIR, 'locales', 'grade' + grade + '-i18n.js');
if (Object.keys(featOut).length) {
  fs.writeFileSync(featPath,
    '/* Auto-generated by build-i18n.js — native translations for the featured breakout. */\n' +
    '(function(){var B=window.BREAKOUT;if(!B)return;var T=' + JSON.stringify(featOut) + ';' +
    'for(var L in T){B.UI[L]=T[L].UI;B.CONTENT[L]=T[L].CONTENT;}})();\n');
}

// ---- concept set ----------------------------------------------------------
let moreCount = 0;
const morePath = path.join(GDIR, 'more.js');
if (fs.existsSync(morePath)) {
  const w = { window: {} };
  eval('(function(window){' + fs.readFileSync(morePath, 'utf8') + '})(w.window)');
  const MORE = w.window.MORE || {};
  const BASE_EN = (w.window.MORE_BASE_UI && w.window.MORE_BASE_UI.en) || {};
  const moreOut = {};
  for (const lang of LANGS) {
    const data = readI18n(lang);
    if (!data || !data.concept) continue;
    const base = Object.assign({}, BASE_EN, data.chrome || {}, data.conceptBase || {});
    const breakouts = {};
    for (const slug of Object.keys(MORE)) {
      const t = data.concept[slug];
      if (!t) continue;
      const e = MORE[slug];
      breakouts[slug] = {
        ui: t.ui || {},
        clues: zipClues(e.clues, t.clues),
        locks: zipLocks(e.locks, t.locks),
      };
    }
    if (Object.keys(breakouts).length) { moreOut[lang] = { base, breakouts }; moreCount++; }
  }
  if (Object.keys(moreOut).length) {
    fs.writeFileSync(path.join(GDIR, 'more-i18n.js'),
      '/* Auto-generated by build-i18n.js — native translations for the concept set. */\n' +
      'window.MORE_I18N = ' + JSON.stringify(moreOut) + ';\n');
  }
}

console.log(`grade${grade}: featured langs [${Object.keys(featOut).join(',') || 'none'}] · concept langs (${moreCount})`);
