#!/usr/bin/env node
/* build-pages.js — write grade<G>/i18n-glossary.js and i18n-eng.js from _glossary|_eng/<lang>.json */
const fs=require('fs'),path=require('path'),ROOT=__dirname,LANGS=['en','es','vi','ar','hi','ur','zh'];
for(const w of [['glossary','i18n-glossary.js'],['eng','i18n-eng.js']]){
  const [widget,reg]=w;const data={};
  for(const l of LANGS){const fp=path.join(ROOT,'_'+widget,l+'.json');if(fs.existsSync(fp))data[l]=JSON.parse(fs.readFileSync(fp,'utf8'));}
  if(!data.en)continue;const grades=Object.keys(data.en.grades);
  for(const g of grades){const dict={};for(const l of LANGS){if(!data[l])continue;dict[l]=(data[l].grades&&data[l].grades[g])||{};}
  fs.writeFileSync(path.join(ROOT,g,reg),'/* Auto-generated by build-pages.js */\nBreakoutI18n.register("science-'+g+'-'+widget+'", '+JSON.stringify(dict)+');\n');}
  console.log('build-pages '+widget+': '+grades.length+' files, langs ['+Object.keys(data).join(', ')+']');
}
