/* build-tickets.js — assemble games/tickets.js from the per-unit source files in games/data/.
   Each data file is self-contained: `window.PST_TICKETS = (window.PST_TICKETS||[]).concat([ … ])`.
   We concatenate them (sorted) so the hub/correlation/dashboard load one file. Run after adding or
   editing any data/<grade>-<unit>.js:  node pst/games/build-tickets.js  */
'use strict';
const fs = require('fs');
const path = require('path');

const GAMES = __dirname;
const DATA = path.join(GAMES, 'data');
const OUT = path.join(GAMES, 'tickets.js');

const files = fs.readdirSync(DATA).filter(f => f.endsWith('.js')).sort();

let out = '/* GENERATED by build-tickets.js — do not edit by hand. Edit the per-unit sources in\n'
  + '   games/data/<grade>-<unit>.js, then re-run `node pst/games/build-tickets.js`. */\n'
  + 'window.PST_TICKETS = window.PST_TICKETS || [];\n\n';

for (const f of files) {
  const body = fs.readFileSync(path.join(DATA, f), 'utf8');
  out += '/* ── ' + f + ' ── */\n' + body.trim() + '\n\n';
}

// sanity: load it in a sandbox and count
let count = 0, entry = 0, exit = 0;
try {
  const sandbox = { window: {} };
  new Function('window', out)(sandbox.window);
  const T = sandbox.window.PST_TICKETS || [];
  count = T.length;
  T.forEach(t => { if (t.type === 'entry') entry++; else if (t.type === 'exit') exit++; });
} catch (e) {
  console.error('BUILD FAILED — a data file has a syntax/runtime error:\n', e.message);
  process.exit(1);
}

fs.writeFileSync(OUT, out);
console.log('tickets.js built from ' + files.length + ' unit file(s): '
  + count + ' tickets (' + entry + ' entry / ' + exit + ' exit).');
